title: Axl S. Cepeda
logo: "/images/profile.jpg?raw=true"

description: >
  Ph.D. Candidate at Temple University (Escalante's Lab). Focusing on ecology, epidemiology, and evolution of infectious diseases, mainly Plasmodium spp.

sidebar_bio: >
  <p style="font-size:12px; text-align: justify;">
    In January 2021, I started my Ph.D. under the guidance of Dr. Ananias A. Escalante at Temple University. Research at the Escalante's Lab focuses on the ecology, epidemiology and evolution of infectious diseases. I am interested in establishing bridges among population genetics, ecological, and evolutionary biology perspectives by interpreting genomic patterns from pathogens (mainly in <i> Plasmodium </i> spp.) and integrating them with environmental or epidemiologic information.
    <br><br>
    <a href="https://igem.temple.edu/people/person/c0ca56d9e60be58ca9380514ed8ac51d" style="color: #9D2235"><b>Escalante-Pacheco Lab</b> ğŸ‘¨ğŸ¼â€ğŸ”¬ğŸ‘¨ğŸ½â€ğŸ’»</a>
    <br>
    <a href="https://igem.temple.edu/" style="color: #9D2235"><b>Department of Biology, iGEM</b> ğŸ“ŠğŸ‘©ğŸ»â€âš•ï¸</a>
    <br>
    <a href="https://www.temple.edu/" style="color: #9D2235"><b>Temple University</b> ğŸ«ğŸ‡ºğŸ‡¸</a>
    <br>
    <a href="https://ciencias.bogota.unal.edu.co/grupos_de_investigacion/biologia/gerph/" style="color: #94B43B"><b>U. Nacional de Colombia, GERPH</b> ğŸ“ğŸ‡¨ğŸ‡´ </a> 
  </p>
  <a href="https://www.linkedin.com/in/AxlCepeda420">View My LinkedIn Profile</a> 
  <a href="https://scholar.google.com/citations?user=Mxpv7hMAAAAJ&hl=en&oi=ao">View My Google Scholar Profile</a>

google_analytics: G-9D67NSSH9Y
theme: jekyll-theme-minimal
