title: Axl S. Cepeda # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p style="font-size:12px"; p align="justify"> 
  In January 2021, I started my Ph.D. under the guidance of Dr. Ananias A. Escalante at Temple University. Research at the Escalante's Lab focuses on the ecology, epidemiology and evolution of infectious diseases. I am interested in establishing bridges among population genetics, ecological, and evolutionary biology perspectives by interpreting genomic patterns from pathogens (mainly in <i> Plasmodium </i> spp.) and integrating them with environmental or epidemiologic information.
  </p>
  <p style="font-size:12px"; p align="justify";style="color:yellow">
  <a href="https://igem.temple.edu/people/person/c0ca56d9e60be58ca9380514ed8ac51d">Escalante's Lab ğŸ‘¨ğŸ¼â€ğŸ”¬ğŸ‘¨ğŸ½â€ğŸ’»</a>
  <a href="https://igem.temple.edu/">Department of Biology, iGEM ğŸ“ŠğŸ‘©ğŸ»â€âš•ï¸</a>
  <a href="https://www.temple.edu/">Temple University ğŸ«ğŸ‡ºğŸ‡¸ </a> 
  </p>
 
  <a href="https://scholar.google.com/citations?user=wkuyeaAAAAAJ&hl=en&oi=ao">View My Google Scholar Profile</a> 
google_analytics: G-9D67NSSH9Y
theme: jekyll-theme-minimal
###<a href="https://asgiraldoc.github.io/pdf/CV_Axl-v.2.pdf">View My <i>Curriculum vitae</i></a> 
###<br><br>
###<a href="https://www.linkedin.com/in/axl-giraldo-cepeda-3881b9151/">View My LinkedIn Profile</a> 
